universe = container
container_image = docker://jeniferqin/endogenius:v2
executable = endogenius.sh

arguments = $(json_config)
# All files needed by the JSON file
transfer_input_files = endogenius.sh, $(mzml_file), $(ms2_file), $(motif_db), $(json_config), $(filtered_fasta)
output = $(out_dir)/logs/EG_R2_$(Cluster)_$(Process).out
error  = $(out_dir)/logs/EG_R2_$(Cluster)_$(Process).err
log    = $(out_dir)/logs/EG_R2_$(Cluster)_$(Process).log

request_cpus = 4
request_memory = 16GB
request_disk = 10GB

transfer_output_files = round2
transfer_output_remaps = "round2 = $(out_dir)/EndoGenius/round2"

queue
