universe = container
container_image = filter_casanovo.sif

executable = filter_casanovo.sh

transfer_input_files = \
    filter_casanovo.py, \
    $(target_mztab), \
    $(decoy_mztab), \
    motif_DB.fasta, \
    new_NPs_since_2010.fasta, \
    np_database.fasta

arguments = $(target_mztab) $(decoy_mztab)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_output_files = results

request_cpus = 1
request_memory = 4GB
request_disk = 5GB

output = logs/filter_$(Cluster)_$(Process).out
error  = logs/filter_$(Cluster)_$(Process).err
log    = logs/filter_$(Cluster)_$(Process).log

queue
