universe        = vanilla
executable      = casanovo.sh

arguments       = $(mgf_file) $(yaml_file) $(ckpt_file) $(out_dir) $(sample)_decoy

# List all required input files for the job
transfer_input_files = casanovo.sh, $(yaml_file), $(ckpt_file), $(mgf_file)

# Output and error logs for monitoring
output          = $(out_dir)/logs/casanovo_d_$(Cluster)_$(Process).out
error           = $(out_dir)/logs/casanovo_d_$(Cluster)_$(Process).err
log             = $(out_dir)/logs/casanovo_d_$(Cluster).log

# Remap the output file.
transfer_output_files = $(sample)_decoy.mztab
transfer_output_remaps = "$(sample)_decoy.mztab = $(out_dir)/Casanovo/$(sample)_decoy.mztab"

# Resource requests
request_cpus    = 6
request_memory  = 32GB
request_disk    = 40GB

# Submit one job
queue
